#!/bin/bash

line_button_modal() {
# usage
    if [ "$1" = "help" ]; then
    echo "Usage: ${0##*/} [options]"
    echo '    text="text"          Line text'
    echo '    icon="icon.svg"      icon file'
    echo '    buttonType="type"    variable: primary, secondary, success, danger, warning, info, light, dark, link'
    echo '    buttonText="text"    Button text'
    echo '    id="id"              id'
    echo '    class="class"        class'
    echo '    border="number"      value: 1~5'
    echo ''
    fi

#It is only necessary to declare the variables that need changes in the content, the file that calls this script already creates the variable that will be used in the script

border="${border:+border border-$border}"

read -d $'' ShowText <<EOF
<div class="row align-items-center bg-secondary text-white rounded py-3  mx-5 $border $class">
    <div class="col .col-sm-8 d-flex align-items-center">
        <img src="./$icon" width="20px" height="20px" class="mx-1"/>
        <label class="form-check-label text-body cursor-pointer ms-1" for="flexSwitchCheckDefault">$text</label>
    </div>
    <div class="col-6 col-sm-4 d-flex justify-content-end">
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-$buttonType" data-bs-toggle="modal" data-bs-target="#$id">
            $buttonText
        </button>
    </div>
</div>
EOF
echo "$ShowText"
}
