#!/bin/bash

# Function to display usage message
usage() {
    echo "Usage: ${0##*/} [options]"
    echo '    -lineText <text>          Line text'
    echo '    -icon <icon.svg>          Icon file'
    echo '    -check <checked>          variable: unchecked, checked, disabled, checked disabled'
    echo '    -run <file.run>           File to be executed when clicking the button'
    echo '    -border <number>     	    1~5'
    echo ''
    exit $1
}

# Loop to process command-line arguments
while (( "$#" )); do
    case "$1" in
        -lineText)
            shift
            lineText="$1"
            ;;
        -icon)
            shift
            icon="$1"
            ;;
        -check)
            shift
            check="$1"
            ;;
        -run)
            shift
            run="$1"
            ;;
        -border)
            shift
            border="border border-${1}"
            ;;
        -id)
            shift
            id="$1"
            ;;
        *)
            usage 1
            ;;
    esac
    shift
done

cat << EOF
<div class="row align-items-center bg-secondary text-white rounded py-3 mx-5 ${border}">
    <div class="col .col-sm-8 d-flex align-items-center">
EOF
if [ -e "${icon}" ];then
cat << EOF
    <img src="./${icon}" width="20px" height="20px" class="mx-1"/>
EOF
fi
cat << EOF
        <label class="form-check-label text-body ms-2" for="${ID}">${lineText}</label>
    </div>
    <div class="col-6 col-sm-4 d-flex justify-content-end">
        <form class="form-check form-switch">
        <input onclick="_run('./${run}')" class="form-check-input" type="checkbox" role="switch" ${check}>
        </form>
    </div>
</div>
EOF
