#!/bin/bash

# Function to display usage message
usage() {
    echo "Usage: ${0##*/} [options]"
    echo '    -lineText <text>     Line text'
    echo '    -icon <icon.svg>     Icon file'
    echo '    -check1 <checked>    variable: unchecked, checked, disabled, checked disabled'
    echo '    -check2 <checked>    variable: unchecked, checked, disabled, checked disabled'
    echo '    -run1 <file.run>     File to be executed when clicking the button'
    echo '    -run2 <file.run>     File to be executed when clicking the button'
    echo ''
    exit $1
}

# Loop to process command-line arguments
while (( "$#" )); do
    case "$1" in
        -lineText)
            shift
            lineText="$1"
            ;;
        -icon)
            shift
            icon="$1"
            ;;
        -check1)
            shift
            check1="$1"
            ;;
        -check2)
            shift
            check2="$1"
            ;;
        -run1)
            shift
            run1="$1"
            ;;
        -run2)
            shift
            run2="$1"
            ;;
        *)
            usage 1
            ;;
    esac
    shift
done

cat << EOF
<section class="box">
    <div class="row align-items-center bg-secondary text-white rounded p-3 mt-4 mx-5 border">
        <div class="col .col-sm-8 d-flex align-items-center">
EOF
if [ -e "${icon}" ];then
cat << EOF
    <img src="./${icon}" width="20px" height="20px" class="mx-1"/>
EOF
fi
cat << EOF
            <label class="form-check-label text-body cursor-pointer ms-2" for="flexSwitchCheckDefault">${lineText}</label>
        </div>
        <div class="col-6 col-sm-4 d-flex justify-content-end">
            <form class="form-check form-switch">
                <input onclick="_run('./${run1}')" class="form-check-input" type="checkbox" role="switch" ${check1}>
            </form>
            <form class="form-check form-switch">
                <input onclick="_run('./${run2}')" class="form-check-input" type="checkbox" role="switch" ${check2}>
            </form>
        </div>
    </div>
</section>
EOF
