#!/bin/bash

# Function to display usage message
usage() {
    echo "Usage: ${0##*/} [options]"
    echo '    -lineText <text>          Line text'
    echo '    -icon <icon.svg>          Icon file'
    echo '    -buttonType <type>        variable: primary, secondary, success, danger, warning, info, light, dark, link'
    echo '    -buttonText <text>        Button text'
    echo '    -run <file.run>           File to be executed when clicking the button'
    echo ''
    exit "$1"
}

# Loop to process command-line arguments
while (( "$#" )); do
    case "$1" in
        -lineText)
            shift
            lineText="$1"
            ;;
        -icon)
            shift
            icon="$1"
            ;;
        -buttonType)
            shift
            buttonType="$1"
            ;;
        -buttonText)
            shift
            buttonText="$1"
            ;;
        -run)
            shift
            run="$1"
            ;;
        *)
            usage 1
            ;;
    esac
    shift
done

cat << EOF
<div class="row align-items-center bg-secondary text-white rounded py-3 mx-5 border">
    <div class="col .col-sm-8 d-flex align-items-center">
        <img src="./$icon" width="20px" height="20px" class="mx-1"/>
        <label class="form-check-label text-body cursor-pointer ms-2" for="flexSwitchCheckDefault">${lineText}</label>
    </div>
    <div class="col-6 col-sm-4 d-flex justify-content-end">
        <form class="form-check form-switch">
        <button onclick="_run('./$run')" type="button" class="btn btn-$buttonType">$buttonText</button>
        </form>
    </div>
</div>
EOF

