#!/bin/bash

# Function to display usage message
usage() {
    echo "Usage: ${0##*/} [options]"
    echo '    -t <text>'
    echo '    -i <icon.svg>'
    echo '    -c <checked>        variable: unchecked, checked, disabled, checked disabled'
    echo '    -r <file.run>       '
    echo ''
    exit $1
}

# Loop to process command-line arguments
while (( "$#" )); do
    case "$1" in
        -t)
            shift
            text="$1"
            ;;
        -i)
            shift
            icon="$1"
            ;;
        -c)
            shift
            checked="$1"
            ;;
        -r)
            shift
            run="$1"
            ;;
        *)
            usage 1
            ;;
    esac
    shift
done

cat << EOF
<div class="row align-items-center bg-secondary text-white rounded py-3  mx-5 border">
    <div class="col .col-sm-8 d-flex align-items-center">
        <img src="./${icon}" width="20px" height="20px" class="mx-1"/>
        <label class="form-check-label text-body cursor-pointer ms-2" for="flexSwitchCheckDefault">${text}</label>
    </div>
    <div class="col-6 col-sm-4 d-flex justify-content-end">
        <form class="form-check form-switch">
        <input onclick="_run('./$run')" class="form-check-input" type="checkbox" role="switch" ${checked}>
        </form>
    </div>
</div>
EOF
