#!/bin/bash

# Function to display usage message
usage() {
    echo "Usage: ${0##*/} [options]"
    echo '    -t <text>'
    echo '    -i <icon.svg>'
    echo '    -c1 <checked>        variable: unchecked, checked, disabled, checked disabled'
    echo '    -c2 <checked>        variable: unchecked, checked, disabled, checked disabled'
    echo '    -r1 <file.run>       '
    echo '    -r2 <file.run>       '
    echo ''
    exit $1
}

# Loop to process command-line arguments
while (( "$#" )); do
    case "$1" in
        -t)
            shift
            text="$1"
            ;;
        -i)
            shift
            icon="$1"
            ;;
        -c1)
            shift
            checked1="$1"
            ;;
        -c2)
            shift
            checked2="$1"
            ;;
        -r1)
            shift
            run1="$1"
            ;;
        -r2)
            shift
            run2="$1"
            ;;
        *)
            usage 1
            ;;
    esac
    shift
done

cat << EOF
<section class="box">
    <div class="row align-items-center bg-secondary text-white rounded-top p-3 mt-4 mx-5 border">
        <div class="col-sm">
            <label class="form-check-label cursor-pointer" for="flexSwitchCheckDefault">${text}</label>
        </div>
        <div class="col-sm d-flex justify-content-end">
            <form class="form-check form-switch">
                <input onclick="_run('./$run1')" class="form-check-input" type="checkbox" role="switch" ${checked1}>
            </form>
            <form class="form-check form-switch">
                <input onclick="_run('./$run2')" class="form-check-input" type="checkbox" role="switch" ${checked2}>
            </form>
        </div>
    </div>
</section>
EOF
