#!/bin/bash

cat << EOF
<nav>
  <div class="nav nav-tabs align-items-center justify-content-center py-3 nav-pills" id="nav-tab" role="tablist">

    <div class="row align-items-center w-100">
      <div class="col d-flex justify-content-center">
      
        <button class="nav-link active btn btn-transparent" id="nav-home-tab" data-bs-toggle="tab" data-bs-target="#nav-home" type="button" role="tab" aria-controls="nav-home" aria-selected="true">Home</button>
      </div>
    
      <div class="col d-flex justify-content-center">
        <button class="nav-link" id="nav-profile-tab" data-bs-toggle="tab" data-bs-target="#nav-profile" type="button" role="tab" aria-controls="nav-profile" aria-selected="false">Profile</button>
      </div>
      
  </div>
</div>
</nav>
  <div class="tab-content" id="nav-tabContent">
  <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab" tabindex="0">...</div>
  <div class="tab-pane fade" id="nav-profile" role="tabpanel" aria-labelledby="nav-profile-tab" tabindex="0">...</div>
</div>
EOF
