#!/bin/bash

# Function to start the HTML document
start() {
    cat << EOF
<section class="box mt-4">
EOF
}

# Function to end the HTML document
end() {
    cat << EOF
</section>
EOF
}

text1() {
cat << EOF
<h1 class="mb-2 mt-3 mx-5">${text}</h1>
EOF
}
text2() {
cat << EOF
<h2 class="mb-2 mt-3 mx-5">${text}</h2>
EOF
}
text3() {
cat << EOF
<h3 class="mb-2 mt-3 mx-5">${text}</h3>
EOF
}
text4() {
cat << EOF
<h4 class="mb-2 mt-3 mx-5">${text}</h4>
EOF
}
text5() {
cat << EOF
<h5 class="mb-2 mt-3 mx-5">${text}</h5>
EOF
}
text6() {
cat << EOF
<h6 class="mb-2 mt-3 mx-5">${text}</h6>
EOF
}

# Function to display usage message
usage() {
    echo "Usage: ${0##*/} [options]"
    echo '    start             '
    echo '    end               '
    echo '    -textH1 <text>        '
    echo '    -textH2 <text>        '
    echo '    -textH3 <text>        '
    echo '    -textH4 <text>        '
    echo '    -textH5 <text>        '
    echo '    -textH6 <text>        '
    echo ''
    exit $1
}

# Loop to process command-line arguments
while (( "$#" )); do
    case "$1" in
        -s|start)
            start_called=true
            ;;
        end)
            end_called=true
            ;;
        -textH1)
            shift
            text="$1"
            text1=true
            ;;
        -textH2)
            shift
            text="$1"
            text2=true
            ;;
        -textH3)
            shift
            text="$1"
            text3=true
            ;;
        -textH4)
            shift
            text="$1"
            text4=true
            ;;
        -textH5)
            shift
            text="$1"
            text5=true
            ;;
        -textH6)
            shift
            text="$1"
            text6=true
            ;;
        *)
            usage 1
            ;;
    esac
    shift
done

# Check if start function should be called
if [ "$start_called" = "true" ]; then
    start
# Check if end function should be called
elif [ "$end_called" = "true" ]; then
    end
fi
if [ "$text1" = "true" ]; then
    text1
fi
if [ "$text2" = "true" ]; then
    text2
fi
if [ "$text3" = "true" ]; then
    text3
fi
if [ "$text4" = "true" ]; then
    text4
fi
if [ "$text5" = "true" ]; then
    text5
fi
if [ "$text6" = "true" ]; then
    text6
fi
