#!/bin/bash

# Function to start the HTML document
start() {
    cat << EOF
<section class="box mt-4">
EOF
}

# Function to end the HTML document
end() {
    cat << EOF
</section>
EOF
}

text5() {
cat << EOF
<h5 class="mb-2 mt-3 mx-5">${text}</h5>
EOF
}

# Function to display usage message
usage() {
    echo "Usage: ${0##*/} [options]"
    echo '    start'
    echo '    end'
    echo '    -t5 <text>       '
    echo ''
    exit $1
}

# Loop to process command-line arguments
while (( "$#" )); do
    case "$1" in
        -s|start)
            start_called=true
            ;;
        end)
            end_called=true
            ;;
        -t5)
            shift
            text="$1"
            text5=true
            ;;
        *)
            usage 1
            ;;
    esac
    shift
done

# Check if start function should be called
if [ "$start_called" = "true" ]; then
    start
# Check if end function should be called
elif [ "$end_called" = "true" ]; then
    end
fi
if [ "$text5" = "true" ]; then
    text5
fi
