#!/bin/bash
# start_html: Start HTML document.
# 2023/16/05

# Function to start the HTML document
start() {
    cat << EOF
<!DOCTYPE html>
<html>
    <head>
        <meta charset='UTF-8'>
        <meta name='viewport' content='width=device-width, initial-scale=1'>
        <title>${title}</title>
        <link rel='icon' href='${icon}'>
        <link rel="stylesheet" href="/usr/share/bigbashview/bcc/css/bootstrap-biglinux.css">
        <link rel="stylesheet" href="/usr/share/javascript/bootstrap/css/bootstrap.css">
    </head>
EOF
}

# Function to end the HTML document
end() {
    cat << EOF
</html>
EOF
}

# Function to display usage message
usage() {
    echo "Usage: ${0##*/} [options]"
    echo '    -t <title>'
    echo '    -r <icon.svg>'
    echo ''
    exit $1
}

# Loop to process command-line arguments
while (( "$#" )); do
    case "$1" in
        -t)
            shift
            title="$1"
            ;;
        -i)
            shift
            icon="$1"
            ;;
        -s|start)
            start_called=true
            ;;
        end)
            end_called=true
            ;;
        *)
            usage 1
            ;;
    esac
    shift
done

# Check if start function should be called
if [ "$start_called" = true ]; then
    start
# Check if end function should be called
elif [ "$end_called" = "true" ]; then
    end
fi
