#!/bin/bash

#use:
#switch checked xpto.run

#checked, disabled, disabled-checked, unchecked
if [ "$1" = "unchecked" ];then
	checked=Default
elif [ "$1" = "checked" ];then
	checked=Checked
elif [ "$1" = "disabled" ];then
	checked=Disabled
elif [ "$1" = "disabled-checked" ];then
	checked="checked disabled"
else
	checked=
fi
	
cat << EOF
<div class="form-check form-switch">
  <input onclick="_run('./$2')" class="form-check-input" type="checkbox" role="switch" $checked>
</div>
EOF
